@TestApp.BaseUrl = http://localhost:5293

GET {{TestApp.BaseUrl}}/api/customers
Accept: application/json

###
POST {{TestApp.BaseUrl}}/api/customers
Accept: application/json
Content-Type: application/json

{
    "Name": "Mac"
}

### Login to get JWT
POST {{TestApp.BaseUrl}}/api/login
Content-Type: application/json

{
  "userName": "Mac",
  "password": "Password"
}

### Delete a customer using JWT
DELETE {{TestApp.BaseUrl}}/api/customers/D2BC5CED-5B27-48A5-15BD-08DDD8407C01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTUyMTAwNzMsImlzcyI6Ik15SXNzdWVyIiwiYXVkIjoiTXlBdWRpZW5jZSJ9.ivK0nGxV_trUiguyi0GtNjhS07JD8iEjrpOos3YlqRY

###
GET {{TestApp.BaseUrl}}/testauth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTUyMDk4OTAsImlzcyI6Ik15SXNzdWVyIiwiYXVkIjoiTXlBdWRpZW5jZSJ9.EgBsdPLF4nm8Pk81VIx64lrxom9EDpLMvAo3ZV1PXlo