@TestApp.BaseUrl = http://localhost:5293

GET {{TestApp.BaseUrl}}/api/customers
Accept: application/json

###
POST {{TestApp.BaseUrl}}/api/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTU1MjMxNzgsImlzcyI6Ik15SXNzdWVyIiwiYXVkIjoiTXlBdWRpZW5jZSJ9.Ug3UDf8sOWicheu4OZH7yNky4wnVV3awFZP6tHmfCjQ

{
    "Name": "Mac"
}

### Login to get JWT
POST {{TestApp.BaseUrl}}/api/login
Content-Type: application/json

{
  "userName": "Mac",
  "password": "Password"
}

### Delete a customer using JWT
DELETE {{TestApp.BaseUrl}}/api/customers/0198aeeb-8564-78d0-8de3-27ff5af8ed56
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTU1MjMyMzUsImlzcyI6Ik15SXNzdWVyIiwiYXVkIjoiTXlBdWRpZW5jZSJ9.4nJOm1Z-ZFSON47khd5izVFwloKHJEwGv2YD4fq6ALU

###
GET {{TestApp.BaseUrl}}/testauth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTWFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTU1MjMyMzUsImlzcyI6Ik15SXNzdWVyIiwiYXVkIjoiTXlBdWRpZW5jZSJ9.4nJOm1Z-ZFSON47khd5izVFwloKHJEwGv2YD4fq6ALU