name: .NET

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --verbosity minimal

            - name: Test with coverage
              run: dotnet test TestApp.Tests/TestApp.Tests.csproj --no-build --settings TestApp.Tests/coverlet/coverage.runsettings --collect:"XPlat Code Coverage"

            - name: Install ReportGenerator
              run: dotnet tool install --global dotnet-reportgenerator-globaltool

            - name: Generate coverage report
              run: |
                  reportgenerator \
                    -reports:"TestApp.Tests/TestResults/*/coverage.cobertura.xml" \
                    -targetdir:"CoverageReport" \
                    -reporttypes:Html;TextSummary

            - name: Show coverage summary in console
              run: cat CoverageReport/Summary.txt

            - name: Upload coverage report artifact
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: CoverageReport/**
