name: .NET Core CI with Coverage

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build solution
              run: dotnet build --no-restore --configuration Release

            - name: Run tests with coverage
              run: |
                  dotnet test \
                    --no-build \
                    --settings TestApp.Tests/coverlet/coverage.runsettings \
                    --collect:"XPlat Code Coverage" \
                    --results-directory TestApp.Tests/TestResults \
                    --verbosity normal

            - name: Install ReportGenerator
              run: dotnet tool install --global dotnet-reportgenerator-globaltool

            - name: Generate coverage report
              run: |
                  export PATH="$PATH:$HOME/.dotnet/tools"
                  reportgenerator \
                    -reports:"TestApp.Tests/TestResults/*/coverage.cobertura.xml" \
                    -targetdir:CoverageReport \
                    -reporttypes:Html;TextSummary

            - name: Upload coverage report artifact
              uses: actions/upload-artifact@v3
              with:
                  name: coverage-report
                  path: CoverageReport
