name: CI Workflow

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup .NET 9
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.x"

            - name: Verify .NET version
              run: dotnet --version

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Install ReportGenerator
              run: dotnet tool install --global dotnet-reportgenerator-globaltool

            - name: Add dotnet tools to PATH
              run: echo "PATH=$HOME/.dotnet/tools:$PATH" >> $GITHUB_ENV

            - name: Make script executable
              run: chmod +x ./TestApp.Tests/CodeCoverage/CodeCoverage.sh

            - name: Run tests and generate coverage
              run: ./TestApp.Tests/CodeCoverage/CodeCoverage.sh
